### ISSUE TITLE
A line between menubar and window manager.

### ISSUE THREAD

**Issue by chuutatsu** [reorr/xfcolorizer#1]
I am using Xfce and GTK 3.22 installed.

In Thunar, the title bar looks okay.
![bug2](https://user-images.githubusercontent.com/24815847/30237473-fca8415c-955c-11e7-8890-4cb6b8ded9c7.png)

But in other apps (Firefox, Xfce Terminal, Gnote) there is a line between menubar and window manager.
![bug1](https://user-images.githubusercontent.com/24815847/30237471-f062bb34-955c-11e7-8139-ed1b072f4b9e.png)

This theme was based on Adapta right? Adapta older versions has such line and I was able to fix it (forget how to, already).

It would be nice if you are able to remove that line too. Or else, update the base theme of this xfcolorizer to Adapta latest version since the latter theme has no such line anymore. Thanks in advance!

**Comment by reorr** [comment]
Sorry for the late reply, i'm too busy with college stuff and a lot other things
So, here we go, in the version 1.2 i've fixed that.

![transmission](https://user-images.githubusercontent.com/10528000/32414574-cbbe4c3a-c25c-11e7-8ef8-a6fe4f153fc9.png)

Thank you for issuing this bug.
Hope that if there's any bug left, you can open issue again and i will try to fix it in my spare time.
